<a href="https://colab.research.google.com/github/kaiocharnai/Projetos/blob/main/Aula%202%20-%20Limpeza%20e%20prepara%C3%A7%C3%A3o%20de%20Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1 - An√°lise de Dados com Pandas

In [3]:
import pandas as pd

In [4]:
# @title
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')

In [ ]:
# @title
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [ ]:
# @title
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [ ]:
# @title
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [ ]:
# @title
df.shape

(133349, 11)

In [ ]:
# @title
# shape √© um atributo, n√£o m√©todo, n√£o usa parenteses

In [ ]:
# @title
linhas, colunas = df.shape[0], df.shape[1]
print('Linhas:', linhas)
print('Colunas', colunas)

Linhas: 133349
Colunas 11

In [ ]:
# @title
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [ ]:
# @title
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')
display(df.head())

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
# @title
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [ ]:
# @title
df['experience_level'].value_counts()

experience_level
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [ ]:
# @title
df['employment_type'].value_counts()

employment_type
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [ ]:
# @title
df['remote_ratio'].value_counts()

remote_ratio
0      105312
100     27718
50        319
Name: count, dtype: int64

In [ ]:
# @title
df['company_size'].value_counts()

company_size
M    129561
L      3574
S       214
Name: count, dtype: int64

In [ ]:
# @title
df.describe(include='object')

,experience_level,employment_type,job_title,salary_currency,employee_residence,company_location,company_size
count,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,95,3
top,SE,FT,Data Scientist,USD,US,US,M
freq,77241,132563,17314,126140,119579,119641,129561

In [ ]:
# @title
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

# Aula 2 - Limpeza e prepara√ß√£o de Dados

In [5]:
df.isnull()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [6]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [7]:
df.isnull().sum()

work_year             10
experience_level       0
employment_type        0
job_title              0
salary                 0
salary_currency        0
salary_in_usd          0
employee_residence     0
remote_ratio           0
company_location       0
company_size           0
dtype: int64

In [9]:
df['work_year'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [10]:
df[df.isnull().any(axis=1)]

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
5588,NaN,SE,FT,Product Manager,184500,USD,184500,US,0,US,M
59692,NaN,MI,FT,Engineer,110000,USD,110000,DE,0,DE,M
59710,NaN,EN,FT,Data Scientist,208800,USD,208800,US,0,US,M
59759,NaN,SE,FT,Software Engineer,135000,USD,135000,US,0,US,M
59789,NaN,SE,FT,Engineer,112000,USD,112000,US,0,US,M
131000,NaN,SE,FT,Machine Learning Engineer,163800,USD,163800,US,0,US,M
131006,NaN,SE,FT,Data Analytics Manager,204500,USD,204500,US,0,US,M
133054,NaN,EN,FT,Data Scientist,40000,USD,40000,JP,100,MY,L
133281,NaN,MI,FT,Machine Learning Engineer,180000,PLN,46597,PL,100,PL,L
133317,NaN,MI,FT,Data Scientist,130000,USD,130000,US,50,US,L

In [17]:
#Criar novo DataFrame e gerar m√©dia

import numpy as np

df_salarios = pd.DataFrame({
    'nome': ['Kaio', 'Kivia', 'Cleide', 'Carlos', 'Kaue'],
    'salario': [np.nan, 4000, np.nan, 6000, 10000]
})
#Calcula a m√©dia e substitui os nulos pela m√©dia e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
#Calcula mediana e substitui os nulos pela mediana
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())
df_salarios

     nome  salario  salario_media  salario_mediana
0    Kaio      NaN        6666.67           6000.0
1   Kivia   4000.0        4000.00           4000.0
2  Cleide      NaN        6666.67           6000.0
3  Carlos   6000.0        6000.00           6000.0
4    Kaue  10000.0       10000.00          10000.0

In [18]:
df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['Preenchido_ffill'] = df_temperaturas['Temperatura'].ffill()
df_temperaturas

       Dia  Temperatura  Preenchido_ffill
0  Segunda         30.0              30.0
1    Ter√ßa          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [19]:
df_temperaturas = pd.DataFrame({
    'Dia': ['Segunda', 'Ter√ßa', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura': [30, np.nan, np.nan, 28, 27]
})

df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

       Dia  Temperatura  Preenchido_bfill
0  Segunda         30.0              30.0
1    Ter√ßa          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [24]:
df_cidades = pd.DataFrame({
    'nome': ['Kaio', 'Kivia', 'Cleide', 'Carlos', 'Kaue'],
    'cidade': ['S√£o Paulo', np.nan, 'Curitiba', np.nan, 'Uberlandia']
})

df_cidades['cidade_preenchida'] = df_cidades['cidade'].fillna('N√£o informado')
df_cidades

     nome      cidade cidade_preenchida
0    Kaio   S√£o Paulo         S√£o Paulo
1   Kivia         NaN     N√£o informado
2  Cleide    Curitiba          Curitiba
3  Carlos         NaN     N√£o informado
4    Kaue  Uberlandia        Uberlandia

In [25]:
df_limpo = df.dropna()

In [27]:
df_limpo.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [31]:
df_limpo.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [32]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  int64
 1   experience_level    133339 non-null  object
 2   employment_type     133339 non-null  object
 3   job_title           133339 non-null  object
 4   salary              133339 non-null  int64
 5   salary_currency     133339 non-null  object
 6   salary_in_usd       133339 non-null  int64
 7   employee_residence  133339 non-null  object
 8   remote_ratio        133339 non-null  int64
 9   company_location    133339 non-null  object
 10  company_size        133339 non-null  object
dtypes: int64(4), object(7)
memory usage: 12.2+ MB

In [30]:
#Converter formato dos dados de Float para Int
df_limpo = df_limpo.assign(work_year=df_limpo['work_year'].astype('int64'))

# Graficos e Hist√≥rias com Dados